### ISSUE TITLE
What is posedir used for?

### ISSUE THREAD

**Issue by chenwwayne** [anders-burov/SkeletonTracker#1]
Hi,anders-burov:

     sorry to bother, may I ask you what is posedir used for? Is this file closely related to SMPL ? 
     LOOKING FORWARD TO YOU REPLY .THANKS

**Comment by andreiburov** [comment]
Hi @ischansgithub,

I guess you're referring to this file https://raw.githubusercontent.com/anders-burov/SkeletonTracker/master/SkeletonTracker/SimpleModel/smpl.posedirs.txt 

It is closely related to SMPL. Checkout the original article http://files.is.tue.mpg.de/black/papers/SMPL2015.pdf, equation 9, it's the _P_ the matrix of all 207 pose blendshapes. One could think of it as of the directions in which to displace a mesh vertex to fix skinning artifacts.

Hope it helps,
Andrei

**Comment by chenwwayne** [comment]
> Hi @ischansgithub,
> 
> I guess you're referring to this file https://raw.githubusercontent.com/anders-burov/SkeletonTracker/master/SkeletonTracker/SimpleModel/smpl.posedirs.txt
> 
> It is closely related to SMPL. Checkout the original article http://files.is.tue.mpg.de/black/papers/SMPL2015.pdf, equation 9, it's the _P_ the matrix of all 207 pose blendshapes. One could think of it as of the directions in which to displace a mesh vertex to fix skinning artifacts.
> 
> Hope it helps,
> Andrei

Much  appreciated , @anders-burov.  May I ask you another question? Is the standard SMPL model and skeleton also closely related? Now that I have generated a customized model from the standard SMPL model, does the skeleton have to be replaced correspondingly so that the program can run?
